[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oragami_asset = "Gi9YACBHAMMNJn7buKaKWsyy5sYMqc3Y9kq4JGyNPQtz"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
