[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cvault-transfer-hook = "3K8V8s8gQtvJVZxW8Z9DvLU4MgginGBx5Yvptb7o6dmT"

[programs.devnet]
cvault-transfer-hook = "3K8V8s8gQtvJVZxW8Z9DvLU4MgginGBx5Yvptb7o6dmT"

[programs.testnet]
cvault-transfer-hook = "3K8V8s8gQtvJVZxW8Z9DvLU4MgginGBx5Yvptb7o6dmT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:/solana-wallet/id.json"

[profile.release]
overflow-checks = true

[workspace]
members = ["programs/cvault-transfer-hook"]