[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
multi-asset-vault = "6Mbzwuw8JdmmQ3uZGw2CepiRLRWo2DgCga5LUhmsha7D"
oragami_vault = "ihUcHpWkfpeE6cH8ycusgyaqNMGGJj8krEyWox1m6aP"

[programs.localnet]
oragami_vault = "ihUcHpWkfpeE6cH8ycusgyaqNMGGJj8krEyWox1m6aP"

[programs.testnet]
oragami_vault = "ihUcHpWkfpeE6cH8ycusgyaqNMGGJj8krEyWox1m6aP"

[provider]
cluster = "devnet"
wallet = "C:/solana-wallet/id.json"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
